### ISSUE TITLE
Publish SMS marketing post

### ISSUE THREAD

**Issue by forgng** [inkOfPixel/inkofpixel.com#78]
# General
- [x] Right before publishing the post, update the post publish date

## English
- [x] Write post
- [x] Write post excerpt
- [x] Check seo title and description
- [x] Write image alt and descriptions.

## Italian
- [x] Write post
- [x] Write post excerpt
- [x] Check seo title and description
- [x] Write image alt and descriptions.

**Comment by dhmacs** [comment]
A couple of feedback on the checklist:

- todos must be detailed actions, they must provide clarity on what you need to be doing. For example, not "excerpt" but "write post excerpt". The more details we add, the less work our brain will need to do to fill the gaps when we come back to do the task, and this provides clarity.
- It seems that something is still missing, for example I can see that page title is still "Magento vs Shopify", let's add to the checklist "Update html head title". Anything else that you can think of that needs to be on the checklist?

I'll review the post shortly, meanwhile you can keep working to mark items on the list as done ✅

**Comment by dhmacs** [comment]
"Image alt and descriptions" still does not reflect what I mentioned above, it's not action, it does not tell you what to do, it merely gives you a scope. Please apply this suggestion to every todo you write. It must be a clear action, that describes what needs to be done

**Comment by dhmacs** [comment]
## Checklist improvements

- [ ] Right before publishing the post, update the post publish date

## Post review

- [ ] What does this mean?
  > Personalized SMS can help achieve the required to create a loyal customer base.

- [ ] What does "bried" mean?
  > Text messages are simple, direct, bried, and personal.

- [ ] Conclusion is... inconclusive.. please write a meaningful conclusion
  > Conclusion SMS marketing can be a very powerful tool if used correctly. If you want to try some of the things you have read in this article try YSMS.

Overall looks pretty good, let's address the issues above, then after localization in italian I think we are go for publish 👍

**Comment by forgng** [comment]
>   > Conclusion SMS marketing can be a very powerful tool if used correctly. If you want to try some of the things you have read in this article try YSMS.

The recent rise of SMS marketing has demonstrated that it can be a very powerful tool if used correctly, but not all businesses have yet adopted it. It's not meant to be a replacement of existing marketing medium like emails, but thanks to its simplicity and attention-grabbing nature can make the difference in getting your customer attention. If you want to try some of the ideas you have read in this article,contact us and we are happy to assist you in setting up YSMS for your Shopify eCommerce.

**Comment by dhmacs** [comment]
# Review

- [x] The excerpt feels like 3 disconnected sentences. It doesn't feel like it's an overview of what the post is about, it feels like they are the first 3 sentences of the post. Take the "Magento vs Shopify" post for instance:
  > Magento and Shopify are two of the most popular platforms that can be used today to build an e-commerce. We share our experience having worked with both platforms and explaining why we have eventually decided to go all in on Shopify

  it's short and it tells you briefly what the post is about. So I would expect the same thing, that ends with something along the line "Find out why and how SMS marketing can make a difference."

- [x] [TLDR]`craete` => create
- [x] [TLDR] Be consistent with punctuation. third bullet should end with a dot
- [x] [Conclusion] add a link to YSMS text, so that the call to action is easy to perform for the reader

I think that after these changes, and the careful localization in italian we're good 👍
